name: CI
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby_version:
          - 2.5
          - 2.6
          - 2.7
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: bundle install && bundle exec appraisal install
      - name: Run tests
        run: bundle exec appraisal rspec
